repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black -l 120 -t py38 ./onto_merger/. ./tests/. setup.py
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: flake8 --max-line-length 120
        types: [python]
        files: ./onto_merger/. ./tests/. setup.py


      - id: flake8-isort
        name: flake8-isort
        stages: [commit]
        language: system
        entry: isort
        types: [python]
        files: ./onto_merger/. ./tests/. setup.py
