"""Produced analysis file names."""

# todo
TABLE_SECTION = "section"
TABLE_SUMMARY = "summary"
TABLE_SECTION_SUMMARY = f"{TABLE_SECTION}_{TABLE_SUMMARY}"
TABLE_NODE_ANALYSIS = "node_analysis"
TABLE_NODE_OBSOLETE_ANALYSIS = "node_obsolete_analysis"
TABLE_MAPPING_ANALYSIS = "mapping_analysis"
TABLE_MERGE_ANALYSIS = "merge_analysis"
TABLE_EDGE_HIERARCHY_ANALYSIS = "edges_hierarchy_analysis"

# new
ANALYSIS_NODE_NAMESPACE_FREQ = "ns_freq_analysis"
ANALYSIS_GENERAL = "general_analysis"
ANALYSIS_PROV = "prov_analysis"
ANALYSIS_TYPE = "type_analysis"
ANALYSIS_MAPPED_NSS = "mapped_nss_analysis"
ANALYSIS_CONNECTED_NSS = "connected_nss_analysis"
ANALYSIS_CONNECTED_NSS_CHART = "connected_nss_analysis_chart"
ANALYSIS_MERGES_NSS = "nss_analysis"
ANALYSIS_MERGES_NSS_FOR_CANONICAL = "nss_canonical_analysis"
GANTT_CHART = "gantt_chart"
HEATMAP_MAPPED_NSS = "mapped_nss_heatmap"
HEATMAP_CONNECTED_NSS = "connected_nss_heatmap"
HEATMAP_MERGED_NSS = "connected_nss_heatmap"
TABLE_STATS = "table_stats"

# columns
COLUMN_COUNT = "count"
COLUMN_FREQ = "freq"
COLUMN_NAMESPACE = "namespace"
COLUMN_NAMESPACE_SOURCE_ID = "namespace_source_id"
COLUMN_NAMESPACE_TARGET_ID = "namespace_target_id"
COLUMN_NAMESPACE_FREQ = "namespace_freq"
