"""Constants used in the report."""

# SECTION NAMES #
SECTION_ALIGNMENT = "alignment"
SECTION_ANALYSIS = "analysis"
SECTION_CONNECTIVITY = "connectivity"
SECTION_DATA_PROFILING = "data_profiling"
SECTION_DATA_TESTS = "data_tests"
SECTION_INPUT = "input"
SECTION_OUTPUT = "output"
SECTION_OVERVIEW = "overview"

REPORT_SECTIONS = [
    SECTION_ALIGNMENT,
    SECTION_ANALYSIS,
    SECTION_CONNECTIVITY,
    SECTION_DATA_PROFILING,
    SECTION_DATA_TESTS,
    SECTION_INPUT,
    SECTION_OUTPUT,
    SECTION_OVERVIEW,
]
